dist: xenial
language: python
python:
  - "3.7"
service:
  - docker
install:
  - pip install -e .
  - pip install codecov
script:
  - coverage run setup.py test
  - tests/e2e/run.sh
after_success:
  - codecov
